spring:
  application:
    name: ranking-system
  datasource:
    url: jdbc:mysql://localhost:3306/insight?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 300   # ✨ 여기 중요: 최대 300 커넥션 풀 확보
      minimum-idle: 10         # 최소 10개 유지
      idle-timeout: 300000     # 5분 (ms)
      max-lifetime: 1800000    # 30분 (ms)
      connection-timeout: 30000 # 30초 (ms)

  jpa:
    hibernate:
      ddl-auto: update  # 실개발 전에는 validate 또는 none 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    root: INFO  # 기본은 INFO
    org.study.rankingsystem: DEBUG  # 우리 프로젝트 패키지 전체
    org.study.rankingsystem.infra.redis.service: DEBUG  # Redis 관련 로직만
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


